#################################################
# APPLICATION
#################################################
spring.application.name=eureka-service
server.port=8761

#################################################
# EUREKA SERVER
#################################################
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

#################################################
# ACTUATOR
#################################################
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

#################################################
# PROMETHEUS
#################################################
management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true

#################################################
# LOGGING
#################################################
logging.level.com.netflix.eureka=INFO
logging.level.org.springframework.cloud.netflix.eureka=INFO