input {
  tcp {
    port => 3535
    codec => json
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "microservice-logs"
  }

  stdout {
    codec => rubydebug
  }
}
